# Generated by Django 4.0.3 on 2022-04-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_contributor_unique_together_contributor_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='permission',
            new_name='permissions',
        ),
    ]
