# Generated by Django 4.0.3 on 2022-03-10 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_rename_assignee_user_id_issue_assignee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author_user',
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(through='application.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
