# Generated by Django 4.0.3 on 2022-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_project_create_time_alter_comment_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='user_id',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(auto_created=True),
        ),
    ]
