# Generated by Django 4.0.3 on 2022-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Auther'), ('CONTRIBUTOR', 'Contributor')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
